"""Generate a manifest of category pages the local wiki wants and prod has.

Imported pages land in categories (squad positions, game tracking, …) whose
קטגוריה: pages aren't part of any season manifest, so they render as
redlinks. This script asks the LOCAL wiki which category pages are missing
(Special:WantedCategories), keeps only those that actually exist on prod
(tracking categories often have no page there either), and writes them to
content-manifests/wanted-categories.manifest.

Run AFTER seeding content (the wanted list comes from the seeded pages):
    uv run python scripts/generate_wanted_categories_manifest.py
    uv run python scripts/download_pages_from_prod.py pages scripts/content-manifests/wanted-categories.manifest
    bash scripts/seed-content.sh wanted-categories
"""
import os
import sys
from pathlib import Path

import requests

LOCAL_API = os.environ.get("MACCABIPEDIA_LOCAL_API", "http://localhost:8080/api.php")
PROD_API = "https://www.maccabipedia.co.il/api.php"


def api_post(endpoint, params):
    response = requests.post(endpoint, data={"format": "json", **params}, timeout=60)
    response.raise_for_status()
    return response.json()


def _paginate(api, params, extract):
    collected = []
    while True:
        data = api(LOCAL_API, params)
        collected += extract(data["query"])
        if "continue" not in data:
            return collected
        params = {**params, **data["continue"]}


def wanted_categories(api=api_post):
    """Categories with local member pages but no local page (Special:WantedCategories)."""
    return _paginate(
        api,
        {"action": "query", "list": "querypage", "qppage": "Wantedcategories", "qplimit": "max"},
        lambda query: [row["title"] for row in query["querypage"]["results"]],
    )


def linked_missing_categories(api=api_post):
    """Categories LINKED from local pages (e.g. squad-position headers) with no
    local page — these have no members, so Special:WantedCategories misses them."""
    linked = _paginate(
        api,
        {"action": "query", "list": "alllinks", "alnamespace": 14, "alunique": 1, "allimit": "max"},
        lambda query: [row["title"] for row in query["alllinks"]],
    )
    existing = _paginate(
        api,
        {"action": "query", "list": "allpages", "apnamespace": 14, "aplimit": "max"},
        lambda query: [row["title"] for row in query["allpages"]],
    )
    return [title for title in linked if title not in set(existing)]


def existing_on_prod(titles, api=api_post):
    """Keep only titles that have an actual page on prod."""
    existing = []
    for start in range(0, len(titles), 50):
        batch = titles[start:start + 50]
        data = api(PROD_API, {"action": "query", "titles": "|".join(batch)})
        for page in data["query"]["pages"].values():
            if "missing" not in page:
                existing.append(page["title"])
    return [title for title in titles if title in set(existing)]  # keep local order


def main():
    out_path = Path(__file__).parent / "content-manifests" / "wanted-categories.manifest"
    # Cumulative: categories already imported stop being "wanted" locally, so
    # each regeneration merges with the committed manifest instead of
    # shrinking to the increment (the prod-existence filter re-runs on all).
    previous = []
    if out_path.is_file():
        previous = [
            line.strip()
            for line in out_path.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.startswith("#")
        ]
    wanted = list(dict.fromkeys(previous + wanted_categories() + linked_missing_categories()))
    titles = existing_on_prod(wanted)
    header = (
        "# Auto-generated by generate_wanted_categories_manifest.py from the\n"
        "# local wiki's Special:WantedCategories, filtered to pages prod has.\n"
        "# Regenerate after seeding new content rather than hand-edit.\n"
    )
    out_path.write_text(header + "\n".join(titles) + "\n", encoding="utf-8")
    skipped = len(wanted) - len(titles)
    print(f"wrote {len(titles)} category titles -> {out_path} ({skipped} wanted but missing on prod too)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
